export type IsSameType<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
    ? (<T>() => T extends B ? 1 : 2) extends <T>() => T extends A ? 1 : 2
      ? true
      : false
    : false;

/**
 * Pick non-symbol and non-method property of a type
 */
export type PickProperty<T> = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [K in keyof T as T[K] extends (...args: any[]) => any ? never : K extends symbol ? never : K]: T[K];
};

export type PickMethod<T> = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [K in keyof T as T[K] extends (...args: any[]) => any ? K : never]: T[K];
};

export type Publicify<T> = {
  -readonly [P in keyof T]: T[P];
};

/**
 * # Get all possible paths of a type, with a maximum depth of 10 to prevent infinite recursion.
 *
 * Generated by DeepSeek-V3.2
 */
export type DeepPaths<T, D extends number = 10> = [D] extends [never]
  ? never
  : T extends object
    ? {
        [K in keyof T]: [K, ...DeepPaths<T[K], Prev[D]>] | [K];
      }[keyof T]
    : never;

// & Auxiliary type to prevent infinite recursion
type Prev = [never, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

export type DeepValue<T, K extends readonly PropertyKey[]> = K extends readonly [infer First, ...infer Rest]
  ? First extends keyof T
    ? Rest extends readonly PropertyKey[]
      ? DeepValue<T[First], Rest>
      : never
    : never
  : T;
