type HTMLElementTypes =
  | HTMLDivElement
  | HTMLSpanElement
  | HTMLParagraphElement
  | HTMLAnchorElement
  | HTMLImageElement
  | HTMLInputElement
  | HTMLButtonElement
  | HTMLFormElement
  | HTMLTableElement
  | HTMLTableRowElement
  | HTMLTableCellElement
  | HTMLUListElement
  | HTMLOListElement
  | HTMLLIElement
  | HTMLSelectElement
  | HTMLOptionElement
  | HTMLTextAreaElement
  | HTMLLabelElement
  | HTMLFieldSetElement
  | HTMLLegendElement
  | HTMLScriptElement
  | HTMLStyleElement
  | HTMLLinkElement
  | HTMLMetaElement
  | HTMLHeadingElement
  | HTMLAudioElement
  | HTMLVideoElement
  | HTMLCanvasElement
  | HTMLIFrameElement
  | HTMLObjectElement
  | HTMLMapElement
  | HTMLAreaElement
  | HTMLDetailsElement
  | HTMLDialogElement
  | HTMLTemplateElement
  | HTMLSlotElement
  | HTMLPictureElement
  | HTMLSourceElement
  | HTMLTimeElement
  | HTMLDataElement
  | HTMLMeterElement
  | HTMLProgressElement
  | HTMLQuoteElement;
